version: '3'
services:
  django:
    build: .
    container_name: django
    command: python /usr/src/Spark/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/Spark
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdbdata:/var/lib/pgsql/data/
    ports:
      - 5433:5433
volumes:
  pgdbdata: